### ISSUE TITLE
Link for Cityscapes motion died

### ISSUE THREAD

**Issue by ChenHoy** [deepmotionseg/SMSnet#3]
Hi,
the link for downloading the Cityscapes motion annotations died. Is there a new one, that works?

Best regards!

**Comment by avalada** [comment]
It exists http://deepmotion.cs.uni-freiburg.de/static/datasets/Cityscapes-Motion.zip

**Comment by ChenHoy** [comment]
Thank you! I guess it was just the direct link from the [website](http://deepmotion.cs.uni-freiburg.de/), which does not work anymore.
